//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace boat.ServiceReferenceTauThuyen_Tuandv {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tuan_dv_TauThuyenModel", Namespace="http://schemas.datacontract.org/2004/07/BoatService")]
    [System.SerializableAttribute()]
    public partial class Tuan_dv_TauThuyenModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MMSIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maloaitauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maquocgiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long taitrongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tentauField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MMSI {
            get {
                return this.MMSIField;
            }
            set {
                if ((object.ReferenceEquals(this.MMSIField, value) != true)) {
                    this.MMSIField = value;
                    this.RaisePropertyChanged("MMSI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string image {
            get {
                return this.imageField;
            }
            set {
                if ((object.ReferenceEquals(this.imageField, value) != true)) {
                    this.imageField = value;
                    this.RaisePropertyChanged("image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ma {
            get {
                return this.maField;
            }
            set {
                if ((object.ReferenceEquals(this.maField, value) != true)) {
                    this.maField = value;
                    this.RaisePropertyChanged("ma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maloaitau {
            get {
                return this.maloaitauField;
            }
            set {
                if ((object.ReferenceEquals(this.maloaitauField, value) != true)) {
                    this.maloaitauField = value;
                    this.RaisePropertyChanged("maloaitau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maquocgia {
            get {
                return this.maquocgiaField;
            }
            set {
                if ((object.ReferenceEquals(this.maquocgiaField, value) != true)) {
                    this.maquocgiaField = value;
                    this.RaisePropertyChanged("maquocgia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long taitrong {
            get {
                return this.taitrongField;
            }
            set {
                if ((this.taitrongField.Equals(value) != true)) {
                    this.taitrongField = value;
                    this.RaisePropertyChanged("taitrong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tentau {
            get {
                return this.tentauField;
            }
            set {
                if ((object.ReferenceEquals(this.tentauField, value) != true)) {
                    this.tentauField = value;
                    this.RaisePropertyChanged("tentau");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceTauThuyen_Tuandv.IServiceTauThuyen")]
    public interface IServiceTauThuyen {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTauThuyen/GetTauThuyenById", ReplyAction="http://tempuri.org/IServiceTauThuyen/GetTauThuyenByIdResponse")]
        boat.ServiceReferenceTauThuyen_Tuandv.Tuan_dv_TauThuyenModel GetTauThuyenById(string ma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTauThuyen/GetTauThuyenById", ReplyAction="http://tempuri.org/IServiceTauThuyen/GetTauThuyenByIdResponse")]
        System.Threading.Tasks.Task<boat.ServiceReferenceTauThuyen_Tuandv.Tuan_dv_TauThuyenModel> GetTauThuyenByIdAsync(string ma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTauThuyen/ThemTauThuyen", ReplyAction="http://tempuri.org/IServiceTauThuyen/ThemTauThuyenResponse")]
        int ThemTauThuyen(boat.ServiceReferenceTauThuyen_Tuandv.Tuan_dv_TauThuyenModel tau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTauThuyen/ThemTauThuyen", ReplyAction="http://tempuri.org/IServiceTauThuyen/ThemTauThuyenResponse")]
        System.Threading.Tasks.Task<int> ThemTauThuyenAsync(boat.ServiceReferenceTauThuyen_Tuandv.Tuan_dv_TauThuyenModel tau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTauThuyen/SuaTauThuyen", ReplyAction="http://tempuri.org/IServiceTauThuyen/SuaTauThuyenResponse")]
        int SuaTauThuyen(boat.ServiceReferenceTauThuyen_Tuandv.Tuan_dv_TauThuyenModel tau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTauThuyen/SuaTauThuyen", ReplyAction="http://tempuri.org/IServiceTauThuyen/SuaTauThuyenResponse")]
        System.Threading.Tasks.Task<int> SuaTauThuyenAsync(boat.ServiceReferenceTauThuyen_Tuandv.Tuan_dv_TauThuyenModel tau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTauThuyen/layDanhSachTau", ReplyAction="http://tempuri.org/IServiceTauThuyen/layDanhSachTauResponse")]
        System.Data.DataSet layDanhSachTau();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTauThuyen/layDanhSachTau", ReplyAction="http://tempuri.org/IServiceTauThuyen/layDanhSachTauResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> layDanhSachTauAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTauThuyen/layDanhSachLoaiTau", ReplyAction="http://tempuri.org/IServiceTauThuyen/layDanhSachLoaiTauResponse")]
        System.Data.DataSet layDanhSachLoaiTau();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTauThuyen/layDanhSachLoaiTau", ReplyAction="http://tempuri.org/IServiceTauThuyen/layDanhSachLoaiTauResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> layDanhSachLoaiTauAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTauThuyen/layDanhSachQuocGia", ReplyAction="http://tempuri.org/IServiceTauThuyen/layDanhSachQuocGiaResponse")]
        System.Data.DataSet layDanhSachQuocGia();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTauThuyen/layDanhSachQuocGia", ReplyAction="http://tempuri.org/IServiceTauThuyen/layDanhSachQuocGiaResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> layDanhSachQuocGiaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTauThuyen/XoaTauThuyen", ReplyAction="http://tempuri.org/IServiceTauThuyen/XoaTauThuyenResponse")]
        int XoaTauThuyen(string maTau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTauThuyen/XoaTauThuyen", ReplyAction="http://tempuri.org/IServiceTauThuyen/XoaTauThuyenResponse")]
        System.Threading.Tasks.Task<int> XoaTauThuyenAsync(string maTau);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceTauThuyenChannel : boat.ServiceReferenceTauThuyen_Tuandv.IServiceTauThuyen, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceTauThuyenClient : System.ServiceModel.ClientBase<boat.ServiceReferenceTauThuyen_Tuandv.IServiceTauThuyen>, boat.ServiceReferenceTauThuyen_Tuandv.IServiceTauThuyen {
        
        public ServiceTauThuyenClient() {
        }
        
        public ServiceTauThuyenClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceTauThuyenClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTauThuyenClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTauThuyenClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public boat.ServiceReferenceTauThuyen_Tuandv.Tuan_dv_TauThuyenModel GetTauThuyenById(string ma) {
            return base.Channel.GetTauThuyenById(ma);
        }
        
        public System.Threading.Tasks.Task<boat.ServiceReferenceTauThuyen_Tuandv.Tuan_dv_TauThuyenModel> GetTauThuyenByIdAsync(string ma) {
            return base.Channel.GetTauThuyenByIdAsync(ma);
        }
        
        public int ThemTauThuyen(boat.ServiceReferenceTauThuyen_Tuandv.Tuan_dv_TauThuyenModel tau) {
            return base.Channel.ThemTauThuyen(tau);
        }
        
        public System.Threading.Tasks.Task<int> ThemTauThuyenAsync(boat.ServiceReferenceTauThuyen_Tuandv.Tuan_dv_TauThuyenModel tau) {
            return base.Channel.ThemTauThuyenAsync(tau);
        }
        
        public int SuaTauThuyen(boat.ServiceReferenceTauThuyen_Tuandv.Tuan_dv_TauThuyenModel tau) {
            return base.Channel.SuaTauThuyen(tau);
        }
        
        public System.Threading.Tasks.Task<int> SuaTauThuyenAsync(boat.ServiceReferenceTauThuyen_Tuandv.Tuan_dv_TauThuyenModel tau) {
            return base.Channel.SuaTauThuyenAsync(tau);
        }
        
        public System.Data.DataSet layDanhSachTau() {
            return base.Channel.layDanhSachTau();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> layDanhSachTauAsync() {
            return base.Channel.layDanhSachTauAsync();
        }
        
        public System.Data.DataSet layDanhSachLoaiTau() {
            return base.Channel.layDanhSachLoaiTau();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> layDanhSachLoaiTauAsync() {
            return base.Channel.layDanhSachLoaiTauAsync();
        }
        
        public System.Data.DataSet layDanhSachQuocGia() {
            return base.Channel.layDanhSachQuocGia();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> layDanhSachQuocGiaAsync() {
            return base.Channel.layDanhSachQuocGiaAsync();
        }
        
        public int XoaTauThuyen(string maTau) {
            return base.Channel.XoaTauThuyen(maTau);
        }
        
        public System.Threading.Tasks.Task<int> XoaTauThuyenAsync(string maTau) {
            return base.Channel.XoaTauThuyenAsync(maTau);
        }
    }
}
