//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace boat.ShipTypeServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="loaitau", Namespace="http://schemas.datacontract.org/2004/07/BoatService.Model")]
    [System.SerializableAttribute()]
    public partial class loaitau : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kieutauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private boat.ShipTypeServiceReference.tauthuyen[] tauthuyensField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tenloaitauField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kieutau {
            get {
                return this.kieutauField;
            }
            set {
                if ((object.ReferenceEquals(this.kieutauField, value) != true)) {
                    this.kieutauField = value;
                    this.RaisePropertyChanged("kieutau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ma {
            get {
                return this.maField;
            }
            set {
                if ((object.ReferenceEquals(this.maField, value) != true)) {
                    this.maField = value;
                    this.RaisePropertyChanged("ma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public boat.ShipTypeServiceReference.tauthuyen[] tauthuyens {
            get {
                return this.tauthuyensField;
            }
            set {
                if ((object.ReferenceEquals(this.tauthuyensField, value) != true)) {
                    this.tauthuyensField = value;
                    this.RaisePropertyChanged("tauthuyens");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tenloaitau {
            get {
                return this.tenloaitauField;
            }
            set {
                if ((object.ReferenceEquals(this.tenloaitauField, value) != true)) {
                    this.tenloaitauField = value;
                    this.RaisePropertyChanged("tenloaitau");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tauthuyen", Namespace="http://schemas.datacontract.org/2004/07/BoatService.Model")]
    [System.SerializableAttribute()]
    public partial class tauthuyen : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MMSIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private boat.ShipTypeServiceReference.hanhtrinh[] hanhtrinhsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private boat.ShipTypeServiceReference.loaitau loaitauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maloaitauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maquocgiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private boat.ShipTypeServiceReference.quocgia quocgiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> taitrongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tentauField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MMSI {
            get {
                return this.MMSIField;
            }
            set {
                if ((object.ReferenceEquals(this.MMSIField, value) != true)) {
                    this.MMSIField = value;
                    this.RaisePropertyChanged("MMSI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public boat.ShipTypeServiceReference.hanhtrinh[] hanhtrinhs {
            get {
                return this.hanhtrinhsField;
            }
            set {
                if ((object.ReferenceEquals(this.hanhtrinhsField, value) != true)) {
                    this.hanhtrinhsField = value;
                    this.RaisePropertyChanged("hanhtrinhs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string image {
            get {
                return this.imageField;
            }
            set {
                if ((object.ReferenceEquals(this.imageField, value) != true)) {
                    this.imageField = value;
                    this.RaisePropertyChanged("image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public boat.ShipTypeServiceReference.loaitau loaitau {
            get {
                return this.loaitauField;
            }
            set {
                if ((object.ReferenceEquals(this.loaitauField, value) != true)) {
                    this.loaitauField = value;
                    this.RaisePropertyChanged("loaitau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ma {
            get {
                return this.maField;
            }
            set {
                if ((object.ReferenceEquals(this.maField, value) != true)) {
                    this.maField = value;
                    this.RaisePropertyChanged("ma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maloaitau {
            get {
                return this.maloaitauField;
            }
            set {
                if ((object.ReferenceEquals(this.maloaitauField, value) != true)) {
                    this.maloaitauField = value;
                    this.RaisePropertyChanged("maloaitau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maquocgia {
            get {
                return this.maquocgiaField;
            }
            set {
                if ((object.ReferenceEquals(this.maquocgiaField, value) != true)) {
                    this.maquocgiaField = value;
                    this.RaisePropertyChanged("maquocgia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public boat.ShipTypeServiceReference.quocgia quocgia {
            get {
                return this.quocgiaField;
            }
            set {
                if ((object.ReferenceEquals(this.quocgiaField, value) != true)) {
                    this.quocgiaField = value;
                    this.RaisePropertyChanged("quocgia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> taitrong {
            get {
                return this.taitrongField;
            }
            set {
                if ((this.taitrongField.Equals(value) != true)) {
                    this.taitrongField = value;
                    this.RaisePropertyChanged("taitrong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tentau {
            get {
                return this.tentauField;
            }
            set {
                if ((object.ReferenceEquals(this.tentauField, value) != true)) {
                    this.tentauField = value;
                    this.RaisePropertyChanged("tentau");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="quocgia", Namespace="http://schemas.datacontract.org/2004/07/BoatService.Model")]
    [System.SerializableAttribute()]
    public partial class quocgia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private boat.ShipTypeServiceReference.tauthuyen[] tauthuyensField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tenquocgiaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ma {
            get {
                return this.maField;
            }
            set {
                if ((object.ReferenceEquals(this.maField, value) != true)) {
                    this.maField = value;
                    this.RaisePropertyChanged("ma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public boat.ShipTypeServiceReference.tauthuyen[] tauthuyens {
            get {
                return this.tauthuyensField;
            }
            set {
                if ((object.ReferenceEquals(this.tauthuyensField, value) != true)) {
                    this.tauthuyensField = value;
                    this.RaisePropertyChanged("tauthuyens");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tenquocgia {
            get {
                return this.tenquocgiaField;
            }
            set {
                if ((object.ReferenceEquals(this.tenquocgiaField, value) != true)) {
                    this.tenquocgiaField = value;
                    this.RaisePropertyChanged("tenquocgia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="hanhtrinh", Namespace="http://schemas.datacontract.org/2004/07/BoatService.Model")]
    [System.SerializableAttribute()]
    public partial class hanhtrinh : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int maField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string matauthuyenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private boat.ShipTypeServiceReference.tauthuyen tauthuyenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> trangthaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private boat.ShipTypeServiceReference.vitritauthuyen[] vitritauthuyensField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ma {
            get {
                return this.maField;
            }
            set {
                if ((this.maField.Equals(value) != true)) {
                    this.maField = value;
                    this.RaisePropertyChanged("ma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string matauthuyen {
            get {
                return this.matauthuyenField;
            }
            set {
                if ((object.ReferenceEquals(this.matauthuyenField, value) != true)) {
                    this.matauthuyenField = value;
                    this.RaisePropertyChanged("matauthuyen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public boat.ShipTypeServiceReference.tauthuyen tauthuyen {
            get {
                return this.tauthuyenField;
            }
            set {
                if ((object.ReferenceEquals(this.tauthuyenField, value) != true)) {
                    this.tauthuyenField = value;
                    this.RaisePropertyChanged("tauthuyen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> trangthai {
            get {
                return this.trangthaiField;
            }
            set {
                if ((this.trangthaiField.Equals(value) != true)) {
                    this.trangthaiField = value;
                    this.RaisePropertyChanged("trangthai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public boat.ShipTypeServiceReference.vitritauthuyen[] vitritauthuyens {
            get {
                return this.vitritauthuyensField;
            }
            set {
                if ((object.ReferenceEquals(this.vitritauthuyensField, value) != true)) {
                    this.vitritauthuyensField = value;
                    this.RaisePropertyChanged("vitritauthuyens");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vitritauthuyen", Namespace="http://schemas.datacontract.org/2004/07/BoatService.Model")]
    [System.SerializableAttribute()]
    public partial class vitritauthuyen : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private boat.ShipTypeServiceReference.hanhtrinh hanhtrinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> kinhdoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int maField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> mahanhtrinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> thoigianField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> vidoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public boat.ShipTypeServiceReference.hanhtrinh hanhtrinh {
            get {
                return this.hanhtrinhField;
            }
            set {
                if ((object.ReferenceEquals(this.hanhtrinhField, value) != true)) {
                    this.hanhtrinhField = value;
                    this.RaisePropertyChanged("hanhtrinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> kinhdo {
            get {
                return this.kinhdoField;
            }
            set {
                if ((this.kinhdoField.Equals(value) != true)) {
                    this.kinhdoField = value;
                    this.RaisePropertyChanged("kinhdo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ma {
            get {
                return this.maField;
            }
            set {
                if ((this.maField.Equals(value) != true)) {
                    this.maField = value;
                    this.RaisePropertyChanged("ma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> mahanhtrinh {
            get {
                return this.mahanhtrinhField;
            }
            set {
                if ((this.mahanhtrinhField.Equals(value) != true)) {
                    this.mahanhtrinhField = value;
                    this.RaisePropertyChanged("mahanhtrinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> thoigian {
            get {
                return this.thoigianField;
            }
            set {
                if ((this.thoigianField.Equals(value) != true)) {
                    this.thoigianField = value;
                    this.RaisePropertyChanged("thoigian");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> vido {
            get {
                return this.vidoField;
            }
            set {
                if ((this.vidoField.Equals(value) != true)) {
                    this.vidoField = value;
                    this.RaisePropertyChanged("vido");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ShipTypeServiceReference.ILoaiTauService")]
    public interface ILoaiTauService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoaiTauService/getListTypesShip1", ReplyAction="http://tempuri.org/ILoaiTauService/getListTypesShip1Response")]
        System.Data.DataSet getListTypesShip1();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoaiTauService/getListTypesShip1", ReplyAction="http://tempuri.org/ILoaiTauService/getListTypesShip1Response")]
        System.Threading.Tasks.Task<System.Data.DataSet> getListTypesShip1Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoaiTauService/InsertTypesShip", ReplyAction="http://tempuri.org/ILoaiTauService/InsertTypesShipResponse")]
        int InsertTypesShip(boat.ShipTypeServiceReference.loaitau _loaitau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoaiTauService/InsertTypesShip", ReplyAction="http://tempuri.org/ILoaiTauService/InsertTypesShipResponse")]
        System.Threading.Tasks.Task<int> InsertTypesShipAsync(boat.ShipTypeServiceReference.loaitau _loaitau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoaiTauService/UpdateTypesShip", ReplyAction="http://tempuri.org/ILoaiTauService/UpdateTypesShipResponse")]
        int UpdateTypesShip(boat.ShipTypeServiceReference.loaitau _loaitau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoaiTauService/UpdateTypesShip", ReplyAction="http://tempuri.org/ILoaiTauService/UpdateTypesShipResponse")]
        System.Threading.Tasks.Task<int> UpdateTypesShipAsync(boat.ShipTypeServiceReference.loaitau _loaitau);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoaiTauServiceChannel : boat.ShipTypeServiceReference.ILoaiTauService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoaiTauServiceClient : System.ServiceModel.ClientBase<boat.ShipTypeServiceReference.ILoaiTauService>, boat.ShipTypeServiceReference.ILoaiTauService {
        
        public LoaiTauServiceClient() {
        }
        
        public LoaiTauServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoaiTauServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoaiTauServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoaiTauServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet getListTypesShip1() {
            return base.Channel.getListTypesShip1();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getListTypesShip1Async() {
            return base.Channel.getListTypesShip1Async();
        }
        
        public int InsertTypesShip(boat.ShipTypeServiceReference.loaitau _loaitau) {
            return base.Channel.InsertTypesShip(_loaitau);
        }
        
        public System.Threading.Tasks.Task<int> InsertTypesShipAsync(boat.ShipTypeServiceReference.loaitau _loaitau) {
            return base.Channel.InsertTypesShipAsync(_loaitau);
        }
        
        public int UpdateTypesShip(boat.ShipTypeServiceReference.loaitau _loaitau) {
            return base.Channel.UpdateTypesShip(_loaitau);
        }
        
        public System.Threading.Tasks.Task<int> UpdateTypesShipAsync(boat.ShipTypeServiceReference.loaitau _loaitau) {
            return base.Channel.UpdateTypesShipAsync(_loaitau);
        }
    }
}
