//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace boat.QuocgiaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QuocgiaService.IQuanLyQuocGia")]
    public interface IQuanLyQuocGia {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyQuocGia/themquocgia", ReplyAction="http://tempuri.org/IQuanLyQuocGia/themquocgiaResponse")]
        bool themquocgia(string maquocgia, string tenquocgia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyQuocGia/themquocgia", ReplyAction="http://tempuri.org/IQuanLyQuocGia/themquocgiaResponse")]
        System.Threading.Tasks.Task<bool> themquocgiaAsync(string maquocgia, string tenquocgia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyQuocGia/suaquocgia", ReplyAction="http://tempuri.org/IQuanLyQuocGia/suaquocgiaResponse")]
        bool suaquocgia(string maquocgia, string tenquocgia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyQuocGia/suaquocgia", ReplyAction="http://tempuri.org/IQuanLyQuocGia/suaquocgiaResponse")]
        System.Threading.Tasks.Task<bool> suaquocgiaAsync(string maquocgia, string tenquocgia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyQuocGia/xoaquocgia", ReplyAction="http://tempuri.org/IQuanLyQuocGia/xoaquocgiaResponse")]
        bool xoaquocgia(string maquocgia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyQuocGia/xoaquocgia", ReplyAction="http://tempuri.org/IQuanLyQuocGia/xoaquocgiaResponse")]
        System.Threading.Tasks.Task<bool> xoaquocgiaAsync(string maquocgia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyQuocGia/layDanhSachquocgia", ReplyAction="http://tempuri.org/IQuanLyQuocGia/layDanhSachquocgiaResponse")]
        System.Data.DataSet layDanhSachquocgia();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyQuocGia/layDanhSachquocgia", ReplyAction="http://tempuri.org/IQuanLyQuocGia/layDanhSachquocgiaResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> layDanhSachquocgiaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQuanLyQuocGiaChannel : boat.QuocgiaService.IQuanLyQuocGia, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QuanLyQuocGiaClient : System.ServiceModel.ClientBase<boat.QuocgiaService.IQuanLyQuocGia>, boat.QuocgiaService.IQuanLyQuocGia {
        
        public QuanLyQuocGiaClient() {
        }
        
        public QuanLyQuocGiaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QuanLyQuocGiaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuanLyQuocGiaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuanLyQuocGiaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool themquocgia(string maquocgia, string tenquocgia) {
            return base.Channel.themquocgia(maquocgia, tenquocgia);
        }
        
        public System.Threading.Tasks.Task<bool> themquocgiaAsync(string maquocgia, string tenquocgia) {
            return base.Channel.themquocgiaAsync(maquocgia, tenquocgia);
        }
        
        public bool suaquocgia(string maquocgia, string tenquocgia) {
            return base.Channel.suaquocgia(maquocgia, tenquocgia);
        }
        
        public System.Threading.Tasks.Task<bool> suaquocgiaAsync(string maquocgia, string tenquocgia) {
            return base.Channel.suaquocgiaAsync(maquocgia, tenquocgia);
        }
        
        public bool xoaquocgia(string maquocgia) {
            return base.Channel.xoaquocgia(maquocgia);
        }
        
        public System.Threading.Tasks.Task<bool> xoaquocgiaAsync(string maquocgia) {
            return base.Channel.xoaquocgiaAsync(maquocgia);
        }
        
        public System.Data.DataSet layDanhSachquocgia() {
            return base.Channel.layDanhSachquocgia();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> layDanhSachquocgiaAsync() {
            return base.Channel.layDanhSachquocgiaAsync();
        }
    }
}
