//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace boat.ConBaoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConBaoService.IConBaoService")]
    public interface IConBaoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConBaoService/layDanhSachBao", ReplyAction="http://tempuri.org/IConBaoService/layDanhSachBaoResponse")]
        System.Data.DataSet layDanhSachBao();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConBaoService/layDanhSachBao", ReplyAction="http://tempuri.org/IConBaoService/layDanhSachBaoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> layDanhSachBaoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConBaoService/themConBao", ReplyAction="http://tempuri.org/IConBaoService/themConBaoResponse")]
        bool themConBao(string ten, string ghiChu, long thoiGianHinhThanh, int maTinhTrang, int trangThai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConBaoService/themConBao", ReplyAction="http://tempuri.org/IConBaoService/themConBaoResponse")]
        System.Threading.Tasks.Task<bool> themConBaoAsync(string ten, string ghiChu, long thoiGianHinhThanh, int maTinhTrang, int trangThai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConBaoService/xoaConBao", ReplyAction="http://tempuri.org/IConBaoService/xoaConBaoResponse")]
        bool xoaConBao(string ma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConBaoService/xoaConBao", ReplyAction="http://tempuri.org/IConBaoService/xoaConBaoResponse")]
        System.Threading.Tasks.Task<bool> xoaConBaoAsync(string ma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConBaoService/themHanhTrinhBao", ReplyAction="http://tempuri.org/IConBaoService/themHanhTrinhBaoResponse")]
        bool themHanhTrinhBao(string maConBao, int trangThai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConBaoService/themHanhTrinhBao", ReplyAction="http://tempuri.org/IConBaoService/themHanhTrinhBaoResponse")]
        System.Threading.Tasks.Task<bool> themHanhTrinhBaoAsync(string maConBao, int trangThai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConBaoService/xoaHanhtrinhBao", ReplyAction="http://tempuri.org/IConBaoService/xoaHanhtrinhBaoResponse")]
        bool xoaHanhtrinhBao(int maHanhTrinh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConBaoService/xoaHanhtrinhBao", ReplyAction="http://tempuri.org/IConBaoService/xoaHanhtrinhBaoResponse")]
        System.Threading.Tasks.Task<bool> xoaHanhtrinhBaoAsync(int maHanhTrinh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConBaoService/themViTriBao", ReplyAction="http://tempuri.org/IConBaoService/themViTriBaoResponse")]
        bool themViTriBao(int maHanhTrinh, float viDo, float kinhDo, long thoiGian, float vanToc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConBaoService/themViTriBao", ReplyAction="http://tempuri.org/IConBaoService/themViTriBaoResponse")]
        System.Threading.Tasks.Task<bool> themViTriBaoAsync(int maHanhTrinh, float viDo, float kinhDo, long thoiGian, float vanToc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConBaoService/xoaViTriBao", ReplyAction="http://tempuri.org/IConBaoService/xoaViTriBaoResponse")]
        bool xoaViTriBao(int ma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConBaoService/xoaViTriBao", ReplyAction="http://tempuri.org/IConBaoService/xoaViTriBaoResponse")]
        System.Threading.Tasks.Task<bool> xoaViTriBaoAsync(int ma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConBaoService/suaViTriBao", ReplyAction="http://tempuri.org/IConBaoService/suaViTriBaoResponse")]
        bool suaViTriBao(int ma, float viDo, float kinhDo, long thoiGian, float vanToc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConBaoService/suaViTriBao", ReplyAction="http://tempuri.org/IConBaoService/suaViTriBaoResponse")]
        System.Threading.Tasks.Task<bool> suaViTriBaoAsync(int ma, float viDo, float kinhDo, long thoiGian, float vanToc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConBaoService/layTinhTrang", ReplyAction="http://tempuri.org/IConBaoService/layTinhTrangResponse")]
        System.Data.DataSet layTinhTrang();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConBaoService/layTinhTrang", ReplyAction="http://tempuri.org/IConBaoService/layTinhTrangResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> layTinhTrangAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConBaoService/layDSHanhTrinh", ReplyAction="http://tempuri.org/IConBaoService/layDSHanhTrinhResponse")]
        System.Data.DataSet layDSHanhTrinh(string maConBao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConBaoService/layDSHanhTrinh", ReplyAction="http://tempuri.org/IConBaoService/layDSHanhTrinhResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> layDSHanhTrinhAsync(string maConBao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConBaoService/layViTriBao", ReplyAction="http://tempuri.org/IConBaoService/layViTriBaoResponse")]
        System.Data.DataSet layViTriBao(int maHanhTrinh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConBaoService/layViTriBao", ReplyAction="http://tempuri.org/IConBaoService/layViTriBaoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> layViTriBaoAsync(int maHanhTrinh);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConBaoServiceChannel : boat.ConBaoService.IConBaoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConBaoServiceClient : System.ServiceModel.ClientBase<boat.ConBaoService.IConBaoService>, boat.ConBaoService.IConBaoService {
        
        public ConBaoServiceClient() {
        }
        
        public ConBaoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConBaoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConBaoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConBaoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet layDanhSachBao() {
            return base.Channel.layDanhSachBao();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> layDanhSachBaoAsync() {
            return base.Channel.layDanhSachBaoAsync();
        }
        
        public bool themConBao(string ten, string ghiChu, long thoiGianHinhThanh, int maTinhTrang, int trangThai) {
            return base.Channel.themConBao(ten, ghiChu, thoiGianHinhThanh, maTinhTrang, trangThai);
        }
        
        public System.Threading.Tasks.Task<bool> themConBaoAsync(string ten, string ghiChu, long thoiGianHinhThanh, int maTinhTrang, int trangThai) {
            return base.Channel.themConBaoAsync(ten, ghiChu, thoiGianHinhThanh, maTinhTrang, trangThai);
        }
        
        public bool xoaConBao(string ma) {
            return base.Channel.xoaConBao(ma);
        }
        
        public System.Threading.Tasks.Task<bool> xoaConBaoAsync(string ma) {
            return base.Channel.xoaConBaoAsync(ma);
        }
        
        public bool themHanhTrinhBao(string maConBao, int trangThai) {
            return base.Channel.themHanhTrinhBao(maConBao, trangThai);
        }
        
        public System.Threading.Tasks.Task<bool> themHanhTrinhBaoAsync(string maConBao, int trangThai) {
            return base.Channel.themHanhTrinhBaoAsync(maConBao, trangThai);
        }
        
        public bool xoaHanhtrinhBao(int maHanhTrinh) {
            return base.Channel.xoaHanhtrinhBao(maHanhTrinh);
        }
        
        public System.Threading.Tasks.Task<bool> xoaHanhtrinhBaoAsync(int maHanhTrinh) {
            return base.Channel.xoaHanhtrinhBaoAsync(maHanhTrinh);
        }
        
        public bool themViTriBao(int maHanhTrinh, float viDo, float kinhDo, long thoiGian, float vanToc) {
            return base.Channel.themViTriBao(maHanhTrinh, viDo, kinhDo, thoiGian, vanToc);
        }
        
        public System.Threading.Tasks.Task<bool> themViTriBaoAsync(int maHanhTrinh, float viDo, float kinhDo, long thoiGian, float vanToc) {
            return base.Channel.themViTriBaoAsync(maHanhTrinh, viDo, kinhDo, thoiGian, vanToc);
        }
        
        public bool xoaViTriBao(int ma) {
            return base.Channel.xoaViTriBao(ma);
        }
        
        public System.Threading.Tasks.Task<bool> xoaViTriBaoAsync(int ma) {
            return base.Channel.xoaViTriBaoAsync(ma);
        }
        
        public bool suaViTriBao(int ma, float viDo, float kinhDo, long thoiGian, float vanToc) {
            return base.Channel.suaViTriBao(ma, viDo, kinhDo, thoiGian, vanToc);
        }
        
        public System.Threading.Tasks.Task<bool> suaViTriBaoAsync(int ma, float viDo, float kinhDo, long thoiGian, float vanToc) {
            return base.Channel.suaViTriBaoAsync(ma, viDo, kinhDo, thoiGian, vanToc);
        }
        
        public System.Data.DataSet layTinhTrang() {
            return base.Channel.layTinhTrang();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> layTinhTrangAsync() {
            return base.Channel.layTinhTrangAsync();
        }
        
        public System.Data.DataSet layDSHanhTrinh(string maConBao) {
            return base.Channel.layDSHanhTrinh(maConBao);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> layDSHanhTrinhAsync(string maConBao) {
            return base.Channel.layDSHanhTrinhAsync(maConBao);
        }
        
        public System.Data.DataSet layViTriBao(int maHanhTrinh) {
            return base.Channel.layViTriBao(maHanhTrinh);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> layViTriBaoAsync(int maHanhTrinh) {
            return base.Channel.layViTriBaoAsync(maHanhTrinh);
        }
    }
}
