//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace boat.BaoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BaoService.IBaoService")]
    public interface IBaoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaoService/DoWork", ReplyAction="http://tempuri.org/IBaoService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaoService/DoWork", ReplyAction="http://tempuri.org/IBaoService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaoService/getListBao", ReplyAction="http://tempuri.org/IBaoService/getListBaoResponse")]
        System.Data.DataSet getListBao();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaoService/getListBao", ReplyAction="http://tempuri.org/IBaoService/getListBaoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> getListBaoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaoService/addToHanhtrinhBao", ReplyAction="http://tempuri.org/IBaoService/addToHanhtrinhBaoResponse")]
        int addToHanhtrinhBao(string ma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaoService/addToHanhtrinhBao", ReplyAction="http://tempuri.org/IBaoService/addToHanhtrinhBaoResponse")]
        System.Threading.Tasks.Task<int> addToHanhtrinhBaoAsync(string ma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaoService/huyHanhtrinhBao", ReplyAction="http://tempuri.org/IBaoService/huyHanhtrinhBaoResponse")]
        void huyHanhtrinhBao(int ma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaoService/huyHanhtrinhBao", ReplyAction="http://tempuri.org/IBaoService/huyHanhtrinhBaoResponse")]
        System.Threading.Tasks.Task huyHanhtrinhBaoAsync(int ma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaoService/addToVitriBao", ReplyAction="http://tempuri.org/IBaoService/addToVitriBaoResponse")]
        void addToVitriBao(int maht, double vi, double ki, long dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaoService/addToVitriBao", ReplyAction="http://tempuri.org/IBaoService/addToVitriBaoResponse")]
        System.Threading.Tasks.Task addToVitriBaoAsync(int maht, double vi, double ki, long dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaoService/getVitriBao", ReplyAction="http://tempuri.org/IBaoService/getVitriBaoResponse")]
        System.Data.DataSet getVitriBao(int maht);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaoService/getVitriBao", ReplyAction="http://tempuri.org/IBaoService/getVitriBaoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> getVitriBaoAsync(int maht);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaoService/getListNewestBao", ReplyAction="http://tempuri.org/IBaoService/getListNewestBaoResponse")]
        System.Data.DataSet getListNewestBao();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaoService/getListNewestBao", ReplyAction="http://tempuri.org/IBaoService/getListNewestBaoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> getListNewestBaoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaoService/layVitriCuoiAll", ReplyAction="http://tempuri.org/IBaoService/layVitriCuoiAllResponse")]
        System.Data.DataSet layVitriCuoiAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaoService/layVitriCuoiAll", ReplyAction="http://tempuri.org/IBaoService/layVitriCuoiAllResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> layVitriCuoiAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBaoServiceChannel : boat.BaoService.IBaoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BaoServiceClient : System.ServiceModel.ClientBase<boat.BaoService.IBaoService>, boat.BaoService.IBaoService {
        
        public BaoServiceClient() {
        }
        
        public BaoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BaoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BaoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BaoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public System.Data.DataSet getListBao() {
            return base.Channel.getListBao();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getListBaoAsync() {
            return base.Channel.getListBaoAsync();
        }
        
        public int addToHanhtrinhBao(string ma) {
            return base.Channel.addToHanhtrinhBao(ma);
        }
        
        public System.Threading.Tasks.Task<int> addToHanhtrinhBaoAsync(string ma) {
            return base.Channel.addToHanhtrinhBaoAsync(ma);
        }
        
        public void huyHanhtrinhBao(int ma) {
            base.Channel.huyHanhtrinhBao(ma);
        }
        
        public System.Threading.Tasks.Task huyHanhtrinhBaoAsync(int ma) {
            return base.Channel.huyHanhtrinhBaoAsync(ma);
        }
        
        public void addToVitriBao(int maht, double vi, double ki, long dt) {
            base.Channel.addToVitriBao(maht, vi, ki, dt);
        }
        
        public System.Threading.Tasks.Task addToVitriBaoAsync(int maht, double vi, double ki, long dt) {
            return base.Channel.addToVitriBaoAsync(maht, vi, ki, dt);
        }
        
        public System.Data.DataSet getVitriBao(int maht) {
            return base.Channel.getVitriBao(maht);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getVitriBaoAsync(int maht) {
            return base.Channel.getVitriBaoAsync(maht);
        }
        
        public System.Data.DataSet getListNewestBao() {
            return base.Channel.getListNewestBao();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getListNewestBaoAsync() {
            return base.Channel.getListNewestBaoAsync();
        }
        
        public System.Data.DataSet layVitriCuoiAll() {
            return base.Channel.layVitriCuoiAll();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> layVitriCuoiAllAsync() {
            return base.Channel.layVitriCuoiAllAsync();
        }
    }
}
